title: Jordan's Blog
description: "Jordan's Projects Blog"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jordan Taylor # add your name
author-img: profile.jpeg # add your photo
about-author: >
    PhD Student Documenting My Journey In Machine Learning.
    <br><br>
    To learn Machine Learning and Reinforcement Learning, check out my educational website <a href="https://central-ai.readthedocs.io/en/latest" target="_blank" style="text-decoration:none">central-ai</a>.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: jordan-wei-taylor # add your Github handle
social-linkedin: jordan-wei-taylor # add your Linkedin handle
social-email: jt2006@bath.ac.uk

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

kramdown:
    auto_ids: true
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
            
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

ntruncate: 30
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
